name: README Anime List
description: '自動抓自己的 Bangumi 追番進度到 README 頁面'

inputs:
  target:
    description: 'Target README'
    required: true
  template:
    description: 'README template file'
    required: true
  render_mode:
    description: 'Render template mode'
    default: 'default'
  bangumi_username:
    description: 'The your Bangumi username or uid'
    required: true
  bangumi_limit:
    description: 'Pull limit for Bangumi list'
    default: 10
  user_agent:
    description: 'User agent for Bangumi API'
    default: 'ycs77/readme-anime-list'

runs:
  using: 'node20'
  main: 'dist/index.mjs'

branding:
  icon: 'list'
  color: 'red'
